name: Notion Auto Update

on:
  schedule:
    - cron: "0 */3 * * *"  # 3시간마다 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 의존성 설치
        run: pip install requests

      - name: Notion 업데이트 실행
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python notion_update.py
